"""update embedding dimension

Revision ID: f2d732b5b183
Revises: e1febc1b9225
Create Date: 2026-04-09 23:45:02.189492

"""
from typing import Sequence, Union
from pgvector.sqlalchemy import Vector
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2d732b5b183'
down_revision: Union[str, Sequence[str], None] = 'e1febc1b9225'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'embedding',
               existing_type=Vector(dim=1536),
               type_=Vector(dim=384),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'embedding',
               existing_type=Vector(dim=384),
               type_=Vector(dim=1536),
               existing_nullable=True)
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### end Alembic commands ###
